name: "vkBot_laravel"
services:
    app:
        build:
            context: .
            args:
                DOCKER_HOST_USER: ${DOCKER_HOST_USER:-app}
                DOCKER_HOST_UID: ${DOCKER_HOST_UID:-1000}
                DOCKER_HOST_GROUP: ${DOCKER_HOST_GROUP:-app}
                DOCKER_HOST_GID: ${DOCKER_HOST_GID:-1000}
        container_name: laravel_app
        working_dir: /var/www
        volumes:
            -   ./:/var/www
            - ./storage:/var/www/storage
        environment:
            TZ: Europe/Moscow
            PHP_INI_SCAN_DIR: ":/usr/local/etc/php/custom.d"
        depends_on:
            -   db

    scheduler:
        build:
            context: .
            args:
                DOCKER_HOST_USER: ${DOCKER_HOST_USER:-app}
                DOCKER_HOST_UID: ${DOCKER_HOST_UID:-1000}
                DOCKER_HOST_GROUP: ${DOCKER_HOST_GROUP:-app}
                DOCKER_HOST_GID: ${DOCKER_HOST_GID:-1000}
        container_name: laravel_scheduler
        working_dir: /var/www
        volumes:
            - ./:/var/www
            - ./storage:/var/www/storage
        environment:
            TZ: Europe/Moscow
            PHP_INI_SCAN_DIR: ":/usr/local/etc/php/custom.d"
        command: php artisan schedule:work
        restart: unless-stopped
        depends_on:
            - db

    queue:
        build:
            context: .
            args:
                DOCKER_HOST_USER: ${DOCKER_HOST_USER:-app}
                DOCKER_HOST_UID: ${DOCKER_HOST_UID:-1000}
                DOCKER_HOST_GROUP: ${DOCKER_HOST_GROUP:-app}
                DOCKER_HOST_GID: ${DOCKER_HOST_GID:-1000}
        container_name: laravel_queue
        working_dir: /var/www
        volumes:
            - ./:/var/www
            - ./storage:/var/www/storage
        environment:
            TZ: Europe/Moscow
            PHP_INI_SCAN_DIR: ":/usr/local/etc/php/custom.d"
        command: php artisan queue:work
        restart: unless-stopped
        depends_on:
            - db

    nginx:
        image: nginx:alpine
        container_name: laravel_nginx
        ports:
            -   "8080:80"
        volumes:
            -   ./:/var/www
            - ./.docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            -   app

    db:
        image: mysql:8.0
        container_name: laravel_db
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_USER: ${DB_USERNAME}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
        ports:
            -   "3306:3306"
        volumes:
            -   db_data:/var/lib/mysql

volumes:
    db_data:

